# Generated by Django 5.0.1 on 2024-01-19 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eComApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='catogory',
            new_name='category',
        ),
    ]
